#!/usr/bin/env python3
"""Pack an MZ load module and relocation metadata into generated C."""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "tools"))

import d2e_analyze


def c_identifier(name: str) -> str:
    result = re.sub(r"[^A-Za-z0-9_]", "_", name)
    return result if result and not result[0].isdigit() else "program_" + result


def emit(image: d2e_analyze.Image, name: str, load_segment: int) -> str:
    if image.format != "mz":
        raise ValueError("MZ packer requires an MZ executable")
    metadata = image.metadata
    lines = [
        "/* Generated by tools/d2e_pack_mz.py. Do not edit. */",
        '#include "d2e/native_runtime.h"',
        "",
        "static const uint8_t program_image[] = {",
    ]
    for offset in range(0, len(image.module_bytes), 12):
        chunk = image.module_bytes[offset : offset + 12]
        lines.append(
            "    " + ", ".join(f"UINT8_C(0x{value:02x})" for value in chunk) + ","
        )
    lines.extend(["};", ""])
    if image.relocations:
        lines.append("static const d2e_mz_relocation program_relocations[] = {")
        for offset, segment in image.relocations:
            lines.append(
                f"    {{UINT16_C(0x{offset:04x}), UINT16_C(0x{segment:04x})}},"
            )
        lines.extend(["};", ""])
        relocation_pointer = "program_relocations"
        relocation_count = (
            "sizeof(program_relocations) / sizeof(program_relocations[0])"
        )
    else:
        relocation_pointer = "NULL"
        relocation_count = "0"
    lines.extend(
        [
            "const d2e_native_program d2e_generated_mz_program = {",
            f'    .name = "{c_identifier(name)}",',
            "    .format = D2E_NATIVE_IMAGE_MZ,",
            f"    .load_segment = UINT16_C(0x{load_segment:04x}),",
            f"    .entry_cs = UINT16_C(0x{metadata['initial_cs']:04x}),",
            f"    .entry_ip = UINT16_C(0x{metadata['initial_ip']:04x}),",
            f"    .initial_ss = UINT16_C(0x{metadata['initial_ss']:04x}),",
            f"    .initial_sp = UINT16_C(0x{metadata['initial_sp']:04x}),",
            "    .image = program_image,",
            "    .image_size = sizeof(program_image),",
            f"    .relocations = {relocation_pointer},",
            f"    .relocation_count = {relocation_count},",
            "    .blocks = NULL,",
            "    .block_count = 0,",
            "    .region = NULL",
            "};",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("input", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    parser.add_argument("--name")
    parser.add_argument("--load-segment", type=lambda value: int(value, 0), default=0x1000)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        image = d2e_analyze.identify(args.input.read_bytes(), "mz", None, None)
        output = emit(image, args.name or args.input.stem, args.load_segment)
    except (OSError, ValueError) as error:
        print(f"MZ packing failed: {error}", file=sys.stderr)
        return 1
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8", newline="\n")
    print(
        f"packed {len(image.module_bytes)} MZ bytes and {len(image.relocations)} "
        f"relocations: {args.output}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
